---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: wordpress-mysql-data
  labels:
    app: wordpress-mysql
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
