---
apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: wordpress-mysql-data
  namespace: default
  labels:
    app: wordpress-mysql
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: wordpress-mysql-data
  resources:
    requests:
      storage: 1Gi
