---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql-nodeport
  labels:
    app: wordpress-mysql
spec:
  ports:
    - port: 3306
      name: mysql
      protocol: TCP
      targetPort: 3306
      nodePort: 30006
  selector:
    app: wordpress-mysql
  type: NodePort