---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-html
  labels:
    app: wordpress
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: wordpress-html
  local:
    path: /var/lib/k3s/default/wordpress-html
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ubuntu-bionic
