---
apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: wordpress-html
  namespace: default
  labels:
    app: wordpress
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: wordpress-html
  resources:
    requests:
      storage: 1Gi
