---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: wordpress-mysql-data
  labels:
    app: wordpress-mysql
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstCustomer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-mysql-data
  labels:
    app: wordpress-mysql
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: wordpress-mysql-data
  local:
    path: /var/lib/k3s/default/wordpress-mysql-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - "*"
---
apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: wordpress-mysql-data
  namespace: default
  labels:
    app: wordpress-mysql
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: wordpress-mysql-data
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
  clusterIP: None