---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    app: traefik-ingress-lb
    app.kubernetes.io/name: traefik-ingress
    app.kubernetes.io/instance: traefik-system
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: k3s-stack
