---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik-ingress-controller
  labels:
    app: traefik-ingress-lb
    app.kubernetes.io/name: traefik-ingress
    app.kubernetes.io/instance: traefik-system
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: k3s-stack
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
